name: Compile PHAR

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@2.13.0
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Install dependencies (lib)
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --classmap-authoritative

    - name: Install dependencies (phar builder)
      run: composer install --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative
      working-directory: tools/phar

    - name: Compile PHAR
      run: vendor/bin/box compile
      working-directory: tools/phar

    - name: Ensure PHAR is OK
      run: build/jolitypo.phar fr_FR README.md
      working-directory: tools/phar
